name: Docker build test

on:
  workflow_dispatch:
    inputs:
      image_type:
        type: choice
        description: Docker image type to build and test
        options: 
          - "jvm"
      kafka_url:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/test/requirements.txt
    - name: Run tests
      working-directory: ./docker
      run: |
        python docker_build_test.py kafka/test -tag=test -type=${{ github.event.inputs.image_type }} -u=${{ github.event.inputs.kafka_url }}
    - name: Run Vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'kafka/test:test'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        output: scan_${{ github.event.inputs.image_type }}.txt
    - uses: actions/upload-artifact@v3
      with:
        name: report_${{ github.event.inputs.image_type }}.html
        path: docker/test/report_${{ github.event.inputs.image_type }}.html
    - uses: actions/upload-artifact@v3
      with:
        name: scan_${{ github.event.inputs.image_type }}.txt
        path: scan_${{ github.event.inputs.image_type }}.txt